CREATE TABLE subscriptions(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    paddle_subscription_id TEXT NOT NULL,
	paddle_plan_id TEXT NOT NULL,
	status TEXT NOT NULL,
	next_bill_date DATETIME NOT NULL,
    user_id INTEGER NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
