CREATE TABLE to_deletes(
    id TEXT NOT NULL PRIMARY KEY,
    pdf_id TEXT NOT NULL,
    delete_time DATETIME NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pdf_id) REFERENCES pdf(id) ON DELETE CASCADE
);
