// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"bg-gray-800 text-gray-200 pt-8 pb-4\"><div class=\"max-w-screen-lg mx-auto flex flex-col items-center\"><a href=\"/\" class=\"text-lg font-bold\">storemypdf</a><!-- Links --><div class=\"mt-4 flex space-x-6\"><a href=\"/api/docs\" class=\"text-gray-400 hover:text-white\">API Docs</a> <a href=\"#\" class=\"text-gray-400 hover:text-white\">Blog</a> <a href=\"#\" class=\"text-gray-400 hover:text-white\">Contact</a> <a href=\"#\" class=\"text-gray-400 hover:text-white\">Privacy</a></div><!-- Copyright --><div class=\"mt-4 text-center text-sm text-gray-500\"><p>© 2024 storemypdf. All rights reserved.</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
