// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func header(isLoggedIn bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"w-full border-b\"><div class=\"max-w-screen-xl mx-auto h-16 flex items-center justify-between px-4\"><!-- Logo --><a href=\"/\" class=\"text-xl font-bold\">storemypdf</a><!-- Mobile Menu Button --><button id=\"mobile-menu-button\" class=\"block lg:hidden px-3 py-2 text-gray-500 hover:text-gray-900\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 6h16M4 12h16m-7 6h7\"></path></svg></button><!-- Desktop Navigation --><nav id=\"desktop-nav\" class=\"hidden lg:flex items-center space-x-5\"><a href=\"/#pricing\" class=\"font-medium text-md text-gray-500 hover:text-gray-900\">Pricing</a> <a href=\"/api/docs\" class=\"font-medium text-md text-gray-500 hover:text-gray-900\">API docs</a> <a href=\"#\" class=\"font-medium text-md text-gray-500 hover:text-gray-900\">Blog</a></nav><!-- Sign In Button -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button hx-post=\"/signout\" onsubmit=\"reloadPage()\" class=\"font-semibold px-3 py-2 rounded text-white bg-sky-600 hover:bg-sky-500 hidden lg:block\">Sign Out</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/signin\" class=\"font-semibold px-3 py-2 rounded text-white bg-sky-600 hover:bg-sky-500 hidden lg:block\">Sign In</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Mobile Navigation --><nav id=\"mobile-nav\" class=\"fixed inset-0 bg-white shadow-lg transform -translate-x-full transition-transform lg:hidden\" aria-label=\"Mobile Navigation\"><button id=\"mobile-close-button\" class=\"absolute top-4 right-4 px-3 py-2 text-gray-500 hover:text-gray-900\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 18L18 6M6 6l12 12\"></path></svg></button><div class=\"flex flex-col items-center mt-16 space-y-4\"><a href=\"/#pricing\" class=\"font-medium text-md text-gray-500 hover:text-gray-900\">Pricing</a> <a href=\"/docs\" class=\"font-medium text-md text-gray-500 hover:text-gray-900\">API docs</a> <a href=\"#\" class=\"font-medium text-md text-gray-500 hover:text-gray-900\">Blog</a> <a href=\"/signin\" class=\"font-semibold px-3 py-2 rounded text-white bg-sky-600 hover:bg-sky-500\">Sign In</a></div></nav></div></header><script>\n    // Get elements\n    const mobileMenuButton = document.getElementById('mobile-menu-button');\n    const mobileNav = document.getElementById('mobile-nav');\n    const mobileCloseButton = document.getElementById('mobile-close-button');\n  \n    // Toggle mobile menu visibility\n    mobileMenuButton.addEventListener('click', () => {\n      mobileNav.style.transform = 'translateX(0)';\n    });\n  \n    // Close mobile menu\n    mobileCloseButton.addEventListener('click', () => {\n      mobileNav.style.transform = 'translateX(-100%)';\n    });\n  \n    // Optionally close mobile menu when clicking outside of it\n    document.addEventListener('click', (event) => {\n      if (!mobileNav.contains(event.target) && !mobileMenuButton.contains(event.target)) {\n        mobileNav.style.transform = 'translateX(-100%)';\n      }\n    });\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
